version: "3.7"
services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: root
        volumes:
            - pgdata:/var/lib/postgresql/data
    webapp:
        build:
            context: .
            dockerfile: WebsiteDockerfile
        depends_on:
            - db
        ports:
            - 5000:5000
volumes:
    pgdata:
